# Generated by Django 4.1.1 on 2022-09-17 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_inter_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Inter',
        ),
    ]
